{% set name = "tvb-framework" %}
{% set version = "2.7" %}
{% set sha256 = "6c16d95071283c3866660132f3f0ea789100d0e3b4c57daacbdb63506be7e29f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - alembic
    - cherrypy
    - cryptography
    - flask
    - flask-restx
    - formencode
    - h5py
    - Jinja2
    - nibabel
    - numpy
    - pandas
    - pillow
    - psutil
    - pyAesCrypt
    - python-keycloak
    - pytest
    - requests
    - scikit-learn
    - scipy
    - simplejson
    - six
    - sqlalchemy
    - tvb-library
    - tvb-data
    - tvb-gdist
    - tvb-storage
    - werkzeug 2.1.2
    - matplotlib 3.5.3
    - psycopg2
    - docutils
    - gevent
    - watchdog

test:
  requires:
    - pip
    - pytest
    - pytest-benchmark
    - pytest-mock
    - beautifulsoup4
    - mock

  commands:
    - pip install requests-toolbelt pynrrd simpleitk wget
    - pip install allensdk --no-deps
    - pip install bctpy siibra xarray
    - python -m wget -o tvb_data.zip https://zenodo.org/record/4263723/files/tvb_data.zip?download=1
    - python -m zipfile -e tvb_data.zip tvb_data
    - cd tvb_data
    - python setup.py develop
    - pytest -o mock_use_standalone_module=true --pyargs tvb.tests.framework --ignore=$PREFIX/lib/python3.10/site-packages/tvb/tests/framework/interfaces/rest/bids_monitor_test.py

  imports:
    - tvb.core.adapters

about:
  home: http://www.thevirtualbrain.com/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A package for performing whole brain simulations
  description: |
    The Virtual Brain Project (TVB Project) has the purpose of offering some |
    modern tools to the Neurosciences community, for computing, simulating |
    and analyzing functional and structural data of human brains. |
    The Virtual Brain framework is a complete framework including: |
    -  a plugable workflow manager; |
    -  a data persistence layer (with a relational DB and File Storage HDF5); |
    -  an HTML5 based user interface; |
    -  visualizers for neuro-science related entities.
    -  REST server and client SDK
  doc_url: http://docs.thevirtualbrain.org/
  dev_url: https://github.com/the-virtual-brain/tvb-root

extra:
  recipe-maintainers:
    - liadomide
    - popaula937
    - romina1601
    - davidbacter01
    
